const ALL_COUNTRIES = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Greenland",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Bermuda",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Cook Islands",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

// Common alternative names and multi-language support
// Includes: Spanish (es), French (fr), German (de), Portuguese (pt), Arabic (ar), Catalan (ca), Italian (it)
export const COUNTRY_ALIASES: Record<string, string[]> = {
  "Afghanistan": ["Afganistán", "Afghanistan", "Afghanistán", "أفغانستان", "Afganistan", "Afghanistan"],
  "Albania": ["Albania", "Albanie", "Albanien", "Albânia", "ألبانيا", "Albània", "Albania"],
  "Algeria": ["Argelia", "Algérie", "Algerien", "Argélia", "الجزائر", "Algèria", "Algeria"],
  "Andorra": ["Andorra", "Andorre", "Andorra", "Andorra", "أندورا", "Andorra", "Andorra"],
  "Angola": ["Angola", "Angola", "Angola", "Angola", "أنغولا", "Angola", "Angola"],
  "Antigua and Barbuda": ["Antigua y Barbuda", "Antigua-et-Barbuda", "Antigua und Barbuda", "Antígua e Barbuda", "أنتيغوا وباربودا", "Antigua i Barbuda", "Antigua e Barbuda"],
  "Argentina": ["Argentina", "Argentine", "Argentinien", "Argentina", "الأرجنتين", "Argentina", "Argentina"],
  "Armenia": ["Armenia", "Arménie", "Armenien", "Armênia", "أرمينيا", "Armènia", "Armenia"],
  "Aruba": ["Aruba", "Aruba", "Aruba", "Aruba", "أروبا", "Aruba", "Aruba"],
  "Australia": ["Australia", "Australie", "Australien", "Austrália", "أستراليا", "Austràlia", "Australia", "Aus", "Oz"],
  "Austria": ["Austria", "Autriche", "Österreich", "Áustria", "النمسا", "Àustria", "Austria"],
  "Azerbaijan": ["Azerbaiyán", "Azerbaïdjan", "Aserbaidschan", "Azerbaijão", "أذربيجان", "Azerbaidjan", "Azerbaigian"],
  "Bahamas": ["Bahamas", "Bahamas", "Bahamas", "Bahamas", "باهاماس", "Bahames", "Bahamas"],
  "Bahrain": ["Baréin", "Bahreïn", "Bahrain", "Bahrein", "البحرين", "Bahrain", "Bahrein"],
  "Bangladesh": ["Bangladés", "Bangladesh", "Bangladesch", "Bangladesh", "بنغلاديش", "Bangla Desh", "Bangladesh"],
  "Barbados": ["Barbados", "Barbade", "Barbados", "Barbados", "باربادوس", "Barbados", "Barbados"],
  "Belarus": ["Bielorrusia", "Biélorussie", "Belarus", "Bielorrússia", "بيلاروسيا", "Bielorússia", "Bielorussia"],
  "Belgium": ["Bélgica", "Belgique", "Belgien", "Bélgica", "بلجيكا", "Bèlgica", "Belgio"],
  "Belize": ["Belice", "Belize", "Belize", "Belize", "بليز", "Belize", "Belize"],
  "Benin": ["Benín", "Bénin", "Benin", "Benin", "بنين", "Benín", "Benin"],
  "Bermuda": ["Bermudas", "Bermudes", "Bermuda", "Bermudas", "برمودا", "Bermudes", "Bermuda"],
  "Bhutan": ["Bután", "Bhoutan", "Bhutan", "Butão", "بوتان", "Bhutan", "Bhutan"],
  "Bolivia": ["Bolivia", "Bolivie", "Bolivien", "Bolívia", "بوليفيا", "Bolívia", "Bolivia"],
  "Bosnia and Herzegovina": ["Bosnia y Herzegovina", "Bosnie-Herzégovine", "Bosnien und Herzegowina", "Bósnia e Herzegovina", "البوسنة والهرسك", "Bòsnia i Hercegovina", "Bosnia ed Erzegovina", "Bosnia", "BiH"],
  "Botswana": ["Botsuana", "Botswana", "Botswana", "Botswana", "بوتسوانا", "Botswana", "Botswana"],
  "Brazil": ["Brasil", "Brésil", "Brasilien", "Brasil", "البرازيل", "Brasil", "Brasile"],
  "Brunei": ["Brunéi", "Brunei", "Brunei", "Brunei", "بروناي", "Brunei", "Brunei"],
  "Bulgaria": ["Bulgaria", "Bulgarie", "Bulgarien", "Bulgária", "بلغاريا", "Bulgària", "Bulgaria"],
  "Burkina Faso": ["Burkina Faso", "Burkina Faso", "Burkina Faso", "Burkina Faso", "بوركينا فاسو", "Burkina Faso", "Burkina Faso"],
  "Burundi": ["Burundi", "Burundi", "Burundi", "Burundi", "بوروندي", "Burundi", "Burundi"],
  "Cabo Verde": ["Cabo Verde", "Cap-Vert", "Kap Verde", "Cabo Verde", "الرأس الأخضر", "Cap Verd", "Capo Verde", "Cape Verde"],
  "Cambodia": ["Camboya", "Cambodge", "Kambodscha", "Camboja", "كمبوديا", "Cambodja", "Cambogia"],
  "Cameroon": ["Camerún", "Cameroun", "Kamerun", "Camarões", "الكاميرون", "Camerun"],
  "Canada": ["Canadá", "Canada", "Kanada", "Canadá", "كندا", "Canadà"],
  "Central African Republic": ["República Centroafricana", "République centrafricaine", "Zentralafrikanische Republik", "República Centro-Africana", "جمهورية أفريقيا الوسطى", "República Centreafricana", "CAR", "Repubblica Centrafricana"],
  "Chad": ["Chad", "Tchad", "Tschad", "Chade", "تشاد", "Txad", "Ciad"],
  "Chile": ["Chile", "Chili", "Chile", "Chile", "تشيلي", "Xile", "Cile"],
  "China": ["China", "Chine", "China", "China", "الصين", "Xina", "Cina"],
  "Colombia": ["Colombia", "Colombie", "Kolumbien", "Colômbia", "كولومبيا", "Colòmbia"],
  "Comoros": ["Comoras", "Comores", "Komoren", "Comores", "جزر القمر", "Comores"],
  "Congo": ["Congo", "Congo", "Kongo", "Congo", "الكونغو", "Congo", "Republic of Congo", "Congo-Brazzaville", "Congo Brazzaville", "Republic of the Congo"],
  "Cook Islands": ["Islas Cook", "Îles Cook", "Cookinseln", "Ilhas Cook", "جزر كوك", "Illes Cook", "Isole Cook"],
  "Costa Rica": ["Costa Rica", "Costa Rica", "Costa Rica", "Costa Rica", "كوستاريكا", "Costa Rica"],
  "Croatia": ["Croacia", "Croatie", "Kroatien", "Croácia", "كرواتيا", "Croàcia", "Croazia"],
  "Cuba": ["Cuba", "Cuba", "Kuba", "Cuba", "كوبا", "Cuba"],
  "Cyprus": ["Chipre", "Chypre", "Zypern", "Chipre", "قبرص", "Xipre", "Cipro"],
  "Czech Republic": ["República Checa", "République tchèque", "Tschechien", "República Tcheca", "التشيك", "República Txeca", "Czechia", "Repubblica Ceca"],
  "Democratic Republic of the Congo": ["República Democrática del Congo", "République démocratique du Congo", "Demokratische Republik Kongo", "República Democrática do Congo", "جمهورية الكونغو الديمقراطية", "República Democràtica del Congo", "DRC", "DR Congo", "Congo-Kinshasa", "Congo Kinshasa", "Zaire", "Repubblica Democratica del Congo"],
  "Denmark": ["Dinamarca", "Danemark", "Dänemark", "Dinamarca", "الدنمارك", "Dinamarca", "Danimarca"],
  "Djibouti": ["Yibuti", "Djibouti", "Dschibuti", "Djibuti", "جيبوتي", "Djibouti", "Gibuti"],
  "Dominica": ["Dominica", "Dominique", "Dominica", "Dominica", "دومينيكا", "Dominica"],
  "Dominican Republic": ["República Dominicana", "République dominicaine", "Dominikanische Republik", "República Dominicana", "جمهورية الدومينيكان", "República Dominicana", "DR", "Repubblica Dominicana"],
  "East Timor": ["Timor Oriental", "Timor oriental", "Osttimor", "Timor-Leste", "تيمور الشرقية", "Timor Oriental", "Timor-Leste", "Timor Leste", "Timor", "Timor Est"],
  "Ecuador": ["Ecuador", "Équateur", "Ecuador", "Equador", "الإكوادور", "Equador"],
  "Egypt": ["Egipto", "Égypte", "Ägypten", "Egito", "مصر", "Egipte", "Egitto"],
  "El Salvador": ["El Salvador", "Salvador", "El Salvador", "El Salvador", "السلفادور", "El Salvador"],
  "Equatorial Guinea": ["Guinea Ecuatorial", "Guinée équatoriale", "Äquatorialguinea", "Guiné Equatorial", "غينيا الاستوائية", "Guinea Equatorial", "Guinea Equatoriale"],
  "Eritrea": ["Eritrea", "Érythrée", "Eritrea", "Eritreia", "إريتريا", "Eritrea"],
  "Estonia": ["Estonia", "Estonie", "Estland", "Estônia", "إستونيا", "Estònia"],
  "Eswatini": ["Esuatini", "Eswatini", "Eswatini", "Essuatíni", "إسواتيني", "Eswatini", "Swaziland"],
  "Ethiopia": ["Etiopía", "Éthiopie", "Äthiopien", "Etiópia", "إثيوبيا", "Etiòpia", "Etiopia"],
  "Fiji": ["Fiyi", "Fidji", "Fidschi", "Fiji", "فيجي", "Fiji", "Figi"],
  "Finland": ["Finlandia", "Finlande", "Finnland", "Finlândia", "فنلندا", "Finlàndia"],
  "France": ["Francia", "France", "Frankreich", "França", "فرنسا", "França"],
  "French Guiana": ["Guayana Francesa", "Guyane française", "Französisch-Guayana", "Guiana Francesa", "غويانا الفرنسية", "Guaiana Francesa", "Guyana Francese"],
  "Gabon": ["Gabón", "Gabon", "Gabun", "Gabão", "الغابون", "Gabon"],
  "Gambia": ["Gambia", "Gambie", "Gambia", "Gâmbia", "غامبيا", "Gàmbia"],
  "Georgia": ["Georgia", "Géorgie", "Georgien", "Geórgia", "جورجيا", "Geòrgia"],
  "Germany": ["Alemania", "Allemagne", "Deutschland", "Alemanha", "ألمانيا", "Alemanya", "Germania"],
  "Ghana": ["Ghana", "Ghana", "Ghana", "Gana", "غانا", "Ghana"],
  "Greece": ["Grecia", "Grèce", "Griechenland", "Grécia", "اليونان", "Grècia"],
  "Greenland": ["Groenlandia", "Groenland", "Grönland", "Groenlândia", "جرينلاند", "Grenlàndia"],
  "Grenada": ["Granada", "Grenade", "Grenada", "Granada", "غرينادا", "Grenada"],
  "Guatemala": ["Guatemala", "Guatemala", "Guatemala", "Guatemala", "غواتيمالا", "Guatemala"],
  "Guinea": ["Guinea", "Guinée", "Guinea", "Guiné", "غينيا", "Guinea"],
  "Guinea Bissau": ["Guinea-Bisáu", "Guinée-Bissau", "Guinea-Bissau", "Guiné-Bissau", "غينيا بيساو", "Guinea Bissau"],
  "Guyana": ["Guyana", "Guyana", "Guyana", "Guiana", "غيانا", "Guyana"],
  "Haiti": ["Haití", "Haïti", "Haiti", "Haiti", "هايتي", "Haití"],
  "Honduras": ["Honduras", "Honduras", "Honduras", "Honduras", "هندوراس", "Hondures"],
  "Hungary": ["Hungría", "Hongrie", "Ungarn", "Hungria", "المجر", "Hongria", "Ungheria"],
  "Iceland": ["Islandia", "Islande", "Island", "Islândia", "آيسلندا", "Islàndia", "Islanda"],
  "India": ["India", "Inde", "Indien", "Índia", "الهند", "Índia"],
  "Indonesia": ["Indonesia", "Indonésie", "Indonesien", "Indonésia", "إندونيسيا", "Indonèsia"],
  "Iran": ["Irán", "Iran", "Iran", "Irã", "إيران", "Iran"],
  "Iraq": ["Irak", "Irak", "Irak", "Iraque", "العراق", "Iraq"],
  "Ireland": ["Irlanda", "Irlande", "Irland", "Irlanda", "أيرلندا", "Irlanda"],
  "Israel": ["Israel", "Israël", "Israel", "Israel", "إسرائيل", "Israel", "Israele"],
  "Italy": ["Italia", "Italie", "Italien", "Itália", "إيطاليا", "Itàlia"],
  "Ivory Coast": ["Costa de Marfil", "Côte d'Ivoire", "Elfenbeinküste", "Costa do Marfim", "ساحل العاج", "Costa d'Ivori", "Cote d'Ivoire", "Cote d Ivoire", "Cote dIvoire", "Côte d'Ivoire", "Costa d'Avorio"],
  "Jamaica": ["Jamaica", "Jamaïque", "Jamaika", "Jamaica", "جامايكا", "Jamaica", "Giamaica"],
  "Japan": ["Japón", "Japon", "Japan", "Japão", "اليابان", "Japó", "Giappone"],
  "Jordan": ["Jordania", "Jordanie", "Jordanien", "Jordânia", "الأردن", "Jordània", "Giordania"],
  "Kazakhstan": ["Kazajistán", "Kazakhstan", "Kasachstan", "Cazaquistão", "كازاخستان", "Kazakhstan", "Kazakistan"],
  "Kenya": ["Kenia", "Kenya", "Kenia", "Quênia", "كينيا", "Kenya"],
  "Kiribati": ["Kiribati", "Kiribati", "Kiribati", "Kiribati", "كيريباتي", "Kiribati"],
  "Kosovo": ["Kosovo", "Kosovo", "Kosovo", "Kosovo", "كوسوفو", "Kosovo"],
  "Kuwait": ["Kuwait", "Koweït", "Kuwait", "Kuwait", "الكويت", "Kuwait"],
  "Kyrgyzstan": ["Kirguistán", "Kirghizistan", "Kirgisistan", "Quirguistão", "قيرغيزستان", "Kirguizistan"],
  "Laos": ["Laos", "Laos", "Laos", "Laos", "لاوس", "Laos"],
  "Latvia": ["Letonia", "Lettonie", "Lettland", "Letônia", "لاتفيا", "Letònia", "Lettonia"],
  "Lebanon": ["Líbano", "Liban", "Libanon", "Líbano", "لبنان", "Líban"],
  "Lesotho": ["Lesoto", "Lesotho", "Lesotho", "Lesoto", "ليسوتو", "Lesotho"],
  "Liberia": ["Liberia", "Liberia", "Liberia", "Libéria", "ليبيريا", "Libèria"],
  "Libya": ["Libia", "Libye", "Libyen", "Líbia", "ليبيا", "Líbia"],
  "Liechtenstein": ["Liechtenstein", "Liechtenstein", "Liechtenstein", "Liechtenstein", "ليختنشتاين", "Liechtenstein"],
  "Lithuania": ["Lituania", "Lituanie", "Litauen", "Lituânia", "ليتوانيا", "Lituània"],
  "Luxembourg": ["Luxemburgo", "Luxembourg", "Luxemburg", "Luxemburgo", "لوكسمبورغ", "Luxemburg", "Lussemburgo"],
  "Madagascar": ["Madagascar", "Madagascar", "Madagaskar", "Madagascar", "مدغشقر", "Madagascar"],
  "Malawi": ["Malaui", "Malawi", "Malawi", "Malawi", "ملاوي", "Malawi"],
  "Malaysia": ["Malasia", "Malaisie", "Malaysia", "Malásia", "ماليزيا", "Malàisia", "Malesia"],
  "Maldives": ["Maldivas", "Maldives", "Malediven", "Maldivas", "المالديف", "Maldives"],
  "Mali": ["Malí", "Mali", "Mali", "Mali", "مالي", "Mali"],
  "Malta": ["Malta", "Malte", "Malta", "Malta", "مالطا", "Malta"],
  "Marshall Islands": ["Islas Marshall", "Îles Marshall", "Marshallinseln", "Ilhas Marshall", "جزر مارشال", "Illes Marshall", "Isole Marshall"],
  "Mauritania": ["Mauritania", "Mauritanie", "Mauretanien", "Mauritânia", "موريتانيا", "Mauritània"],
  "Mauritius": ["Mauricio", "Maurice", "Mauritius", "Maurícia", "موريشيوس", "Maurici"],
  "Mexico": ["México", "Mexique", "Mexiko", "México", "المكسيك", "Mèxic", "Messico"],
  "Micronesia": ["Micronesia", "Micronésie", "Mikronesien", "Micronésia", "ميكرونيسيا", "Micronèsia"],
  "Moldova": ["Moldavia", "Moldavie", "Moldau", "Moldávia", "مولدوفا", "Moldàvia"],
  "Monaco": ["Mónaco", "Monaco", "Monaco", "Mônaco", "موناكو", "Mònaco"],
  "Mongolia": ["Mongolia", "Mongolie", "Mongolei", "Mongólia", "منغوليا", "Mongòlia"],
  "Montenegro": ["Montenegro", "Monténégro", "Montenegro", "Montenegro", "الجبل الأسود", "Montenegro"],
  "Morocco": ["Marruecos", "Maroc", "Marokko", "Marrocos", "المغرب", "Marroc", "Marocco"],
  "Mozambique": ["Mozambique", "Mozambique", "Mosambik", "Moçambique", "موزمبيق", "Moçambic", "Mozambico"],
  "Myanmar": ["Birmania", "Birmanie", "Myanmar", "Myanmar", "ميانمار", "Myanmar", "Burma"],
  "Namibia": ["Namibia", "Namibie", "Namibia", "Namíbia", "ناميبيا", "Namíbia"],
  "Nauru": ["Nauru", "Nauru", "Nauru", "Nauru", "ناورو", "Nauru"],
  "Nepal": ["Nepal", "Népal", "Nepal", "Nepal", "نيبال", "Nepal"],
  "Netherlands": ["Países Bajos", "Pays-Bas", "Niederlande", "Países Baixos", "هولندا", "Països Baixos", "Holland", "Holanda", "Paesi Bassi"],
  "New Zealand": ["Nueva Zelanda", "Nouvelle-Zélande", "Neuseeland", "Nova Zelândia", "نيوزيلندا", "Nova Zelanda", "NZ", "Kiwi", "Nuova Zelanda"],
  "Nicaragua": ["Nicaragua", "Nicaragua", "Nicaragua", "Nicarágua", "نيكاراغوا", "Nicaragua"],
  "Niger": ["Níger", "Niger", "Niger", "Níger", "النيجر", "Níger"],
  "Nigeria": ["Nigeria", "Nigeria", "Nigeria", "Nigéria", "نيجيريا", "Nigèria"],
  "North Korea": ["Corea del Norte", "Corée du Nord", "Nordkorea", "Coreia do Norte", "كوريا الشمالية", "Corea del Nord", "DPRK", "Democratic People's Republic of Korea", "NK"],
  "North Macedonia": ["Macedonia del Norte", "Macédoine du Nord", "Nordmazedonien", "Macedônia do Norte", "مقدونيا الشمالية", "Macedònia del Nord", "Macedonia", "FYROM", "Macedonia del Nord"],
  "Norway": ["Noruega", "Norvège", "Norwegen", "Noruega", "النرويج", "Noruega", "Svalbard", "Norvegia"],
  "Oman": ["Omán", "Oman", "Oman", "Omã", "عمان", "Oman"],
  "Pakistan": ["Pakistán", "Pakistan", "Pakistan", "Paquistão", "باكستان", "Pakistan"],
  "Palau": ["Palaos", "Palaos", "Palau", "Palau", "بالاو", "Palau"],
  "Palestine": ["Palestina", "Palestine", "Palästina", "Palestina", "فلسطين", "Palestina"],
  "Panama": ["Panamá", "Panama", "Panama", "Panamá", "بنما", "Panamà"],
  "Papua New Guinea": ["Papúa Nueva Guinea", "Papouasie-Nouvelle-Guinée", "Papua-Neuguinea", "Papua-Nova Guiné", "بابوا غينيا الجديدة", "Papua Nova Guinea", "PNG", "Papua Nuova Guinea"],
  "Paraguay": ["Paraguay", "Paraguay", "Paraguay", "Paraguai", "باراغواي", "Paraguai"],
  "Peru": ["Perú", "Pérou", "Peru", "Peru", "بيرو", "Perú", "Perù"],
  "Philippines": ["Filipinas", "Philippines", "Philippinen", "Filipinas", "الفلبين", "Filipines", "Filippine"],
  "Poland": ["Polonia", "Pologne", "Polen", "Polônia", "بولندا", "Polònia"],
  "Portugal": ["Portugal", "Portugal", "Portugal", "Portugal", "البرتغال", "Portugal", "Portogallo"],
  "Puerto Rico": ["Puerto Rico", "Porto Rico", "Puerto Rico", "Porto Rico", "بورتوريكو", "Puerto Rico"],
  "Qatar": ["Catar", "Qatar", "Katar", "Catar", "قطر", "Qatar"],
  "Romania": ["Rumania", "Roumanie", "Rumänien", "Romênia", "رومانيا", "Romania"],
  "Russia": ["Rusia", "Russie", "Russland", "Rússia", "روسيا", "Rússia", "Russian Federation"],
  "Rwanda": ["Ruanda", "Rwanda", "Ruanda", "Ruanda", "رواندا", "Ruanda"],
  "Saint Kitts and Nevis": ["San Cristóbal y Nieves", "Saint-Christophe-et-Niévès", "St. Kitts und Nevis", "São Cristóvão e Nevis", "سانت كيتس ونيفيس", "Saint Kitts i Nevis", "St Kitts", "Saint Kitts", "SKN", "Saint Kitts e Nevis"],
  "Saint Lucia": ["Santa Lucía", "Sainte-Lucie", "St. Lucia", "Santa Lúcia", "سانت لوسيا", "Saint Lucia", "St Lucia", "Santa Lucia"],
  "Saint Vincent and the Grenadines": ["San Vicente y las Granadinas", "Saint-Vincent-et-les-Grenadines", "St. Vincent und die Grenadinen", "São Vicente e Granadinas", "سانت فينسنت والغرينادين", "Saint Vincent i les Grenadines", "St Vincent", "Saint Vincent", "SVG", "Saint Vincent e Grenadine"],
  "Samoa": ["Samoa", "Samoa", "Samoa", "Samoa", "ساموا", "Samoa"],
  "San Marino": ["San Marino", "Saint-Marin", "San Marino", "San Marino", "سان مارينو", "San Marino"],
  "Sao Tome and Principe": ["Santo Tomé y Príncipe", "Sao Tomé-et-Principe", "São Tomé und Príncipe", "São Tomé e Príncipe", "ساو تومي وبرينسيب", "São Tomé i Príncipe", "Sao Tome", "São Tomé"],
  "Saudi Arabia": ["Arabia Saudita", "Arabie saoudite", "Saudi-Arabien", "Arábia Saudita", "السعودية", "Aràbia Saudita"],
  "Senegal": ["Senegal", "Sénégal", "Senegal", "Senegal", "السنغال", "Senegal"],
  "Serbia": ["Serbia", "Serbie", "Serbien", "Sérvia", "صربيا", "Sèrbia"],
  "Seychelles": ["Seychelles", "Seychelles", "Seychellen", "Seychelles", "سيشل", "Seychelles"],
  "Sierra Leone": ["Sierra Leona", "Sierra Leone", "Sierra Leone", "Serra Leoa", "سيراليون", "Sierra Leone"],
  "Singapore": ["Singapur", "Singapour", "Singapur", "Singapura", "سنغافورة", "Singapur"],
  "Slovakia": ["Eslovaquia", "Slovaquie", "Slowakei", "Eslováquia", "سلوفاكيا", "Eslovàquia", "Slovacchia"],
  "Slovenia": ["Eslovenia", "Slovénie", "Slowenien", "Eslovênia", "سلوفينيا", "Eslovènia"],
  "Solomon Islands": ["Islas Salomón", "Îles Salomon", "Salomonen", "Ilhas Salomão", "جزر سليمان", "Illes Salomó", "Isole Salomone"],
  "Somalia": ["Somalia", "Somalie", "Somalia", "Somália", "الصومال", "Somàlia"],
  "South Africa": ["Sudáfrica", "Afrique du Sud", "Südafrika", "África do Sul", "جنوب أفريقيا", "Sud-àfrica", "RSA", "SA", "Sudafrica"],
  "South Korea": ["Corea del Sur", "Corée du Sud", "Südkorea", "Coreia do Sul", "كوريا الجنوبية", "Corea del Sud", "Korea", "Republic of Korea", "ROK", "SK", "S Korea"],
  "South Sudan": ["Sudán del Sur", "Soudan du Sud", "Südsudan", "Sudão do Sul", "جنوب السودان", "Sudan del Sud"],
  "Spain": ["España", "Espagne", "Spanien", "Espanha", "إسبانيا", "Espanya", "Spagna"],
  "Sri Lanka": ["Sri Lanka", "Sri Lanka", "Sri Lanka", "Sri Lanka", "سريلانكا", "Sri Lanka"],
  "Sudan": ["Sudán", "Soudan", "Sudan", "Sudão", "السودان", "Sudan"],
  "Suriname": ["Surinam", "Suriname", "Suriname", "Suriname", "سورينام", "Surinam"],
  "Sweden": ["Suecia", "Suède", "Schweden", "Suécia", "السويد", "Suècia", "Svezia"],
  "Switzerland": ["Suiza", "Suisse", "Schweiz", "Suíça", "سويسرا", "Suïssa", "Swiss", "Svizzera"],
  "Syria": ["Siria", "Syrie", "Syrien", "Síria", "سوريا", "Síria"],
  "Taiwan": ["Taiwán", "Taïwan", "Taiwan", "Taiwan", "تايوان", "Taiwan"],
  "Tajikistan": ["Tayikistán", "Tadjikistan", "Tadschikistan", "Tajiquistão", "طاجيكستان", "Tadjikistan", "Tagikistan"],
  "Tanzania": ["Tanzania", "Tanzanie", "Tansania", "Tanzânia", "تنزانيا", "Tanzània", "TZ"],
  "Thailand": ["Tailandia", "Thaïlande", "Thailand", "Tailândia", "تايلاند", "Tailàndia", "Thailandia"],
  "Timor Leste": ["Timor Oriental", "Timor oriental", "Osttimor", "Timor-Leste", "تيمور الشرقية", "Timor Oriental", "Timor Est"],
  "Togo": ["Togo", "Togo", "Togo", "Togo", "توغو", "Togo"],
  "Tonga": ["Tonga", "Tonga", "Tonga", "Tonga", "تونغا", "Tonga"],
  "Trinidad and Tobago": ["Trinidad y Tobago", "Trinité-et-Tobago", "Trinidad und Tobago", "Trinidad e Tobago", "ترينيداد وتوباغو", "Trinitat i Tobago", "Trinidad", "T&T"],
  "Tunisia": ["Túnez", "Tunisie", "Tunesien", "Tunísia", "تونس", "Tunísia"],
  "Turkey": ["Turquía", "Turquie", "Türkei", "Turquia", "تركيا", "Turquia", "Turchia"],
  "Turkmenistan": ["Turkmenistán", "Turkménistan", "Turkmenistan", "Turcomenistão", "تركمانستان", "Turkmenistan"],
  "Tuvalu": ["Tuvalu", "Tuvalu", "Tuvalu", "Tuvalu", "توفالو", "Tuvalu"],
  "Uganda": ["Uganda", "Ouganda", "Uganda", "Uganda", "أوغندا", "Uganda"],
  "Ukraine": ["Ucrania", "Ukraine", "Ukraine", "Ucrânia", "أوكرانيا", "Ucraïna", "Ucraina"],
  "United Arab Emirates": ["Emiratos Árabes Unidos", "Émirats arabes unis", "Vereinigte Arabische Emirate", "Emirados Árabes Unidos", "الإمارات العربية المتحدة", "Emirats Àrabs Units", "UAE", "Emirates", "U.A.E", "Emirati Arabi Uniti"],
  "United Kingdom": ["Reino Unido", "Royaume-Uni", "Vereinigtes Königreich", "Reino Unido", "المملكة المتحدة", "Regne Unit", "UK", "Britain", "Great Britain", "England", "U.K", "GB", "Regno Unito"],
  "United States": ["Estados Unidos", "États-Unis", "Vereinigte Staaten", "Estados Unidos", "الولايات المتحدة", "Estats Units", "USA", "US", "United States of America", "America", "U.S.A", "U.S", "States", "EUA", "Stati Uniti"],
  "Uruguay": ["Uruguay", "Uruguay", "Uruguay", "Uruguai", "أوروغواي", "Uruguai"],
  "Uzbekistan": ["Uzbekistán", "Ouzbékistan", "Usbekistan", "Uzbequistão", "أوزبكستان", "Uzbekistan"],
  "Vanuatu": ["Vanuatu", "Vanuatu", "Vanuatu", "Vanuatu", "فانواتو", "Vanuatu"],
  "Vatican City": ["Ciudad del Vaticano", "Vatican", "Vatikanstadt", "Cidade do Vaticano", "الفاتيكان", "Ciutat del Vaticà", "Città del Vaticano"],
  "Venezuela": ["Venezuela", "Venezuela", "Venezuela", "Venezuela", "فنزويلا", "Veneçuela"],
  "Vietnam": ["Vietnam", "Viêt Nam", "Vietnam", "Vietnã", "فيتنام", "Vietnam"],
  "Western Sahara": ["Sáhara Occidental", "Sahara occidental", "Westsahara", "Saara Ocidental", "الصحراء الغربية", "Sàhara Occidental", "Sahara Occidentale"],
  "Yemen": ["Yemen", "Yémen", "Jemen", "Iêmen", "اليمن", "Iemen"],
  "Zambia": ["Zambia", "Zambie", "Sambia", "Zâmbia", "زامبيا", "Zàmbia"],
  "Zimbabwe": ["Zimbabue", "Zimbabwe", "Simbabwe", "Zimbábue", "زيمبابوي", "Zimbabwe"],
};

export function normalizeCountryName(input: string): string {
  return input
    .toLowerCase()
    .trim()
    .replace(/[^\p{L}\s]/gu, "")
    .replace(/\s+/g, " ");
}

export function findCountryMatch(input: string): string | null {
  const normalized = normalizeCountryName(input);

  // Direct match
  for (const country of ALL_COUNTRIES) {
    if (normalizeCountryName(country) === normalized) {
      return country;
    }
  }

  // Alias match
  for (const [country, aliases] of Object.entries(COUNTRY_ALIASES)) {
    for (const alias of aliases) {
      if (normalizeCountryName(alias) === normalized) {
        return country;
      }
    }
  }

  return null;
}

export interface CountryData {
  name: string;
  continent:
    | "Africa"
    | "Asia"
    | "Europe"
    | "North America"
    | "South America"
    | "Oceania";
  iso: string;
}

export const COUNTRY_DATA: CountryData[] = [
  { name: "Afghanistan", continent: "Asia", iso: "AF" },
  { name: "Albania", continent: "Europe", iso: "AL" },
  { name: "Algeria", continent: "Africa", iso: "DZ" },
  { name: "Greenland", continent: "North America", iso: "GL" },
  { name: "Andorra", continent: "Europe", iso: "AD" },
  { name: "Angola", continent: "Africa", iso: "AO" },
  { name: "Antigua and Barbuda", continent: "North America", iso: "AG" },
  { name: "Argentina", continent: "South America", iso: "AR" },
  { name: "Armenia", continent: "Asia", iso: "AM" },
  { name: "Aruba", continent: "North America", iso: "AW" },
  { name: "Australia", continent: "Oceania", iso: "AU" },
  { name: "Austria", continent: "Europe", iso: "AT" },
  { name: "Azerbaijan", continent: "Asia", iso: "AZ" },
  { name: "Bahamas", continent: "North America", iso: "BS" },
  { name: "Bahrain", continent: "Asia", iso: "BH" },
  { name: "Bangladesh", continent: "Asia", iso: "BD" },
  { name: "Barbados", continent: "North America", iso: "BB" },
  { name: "Belarus", continent: "Europe", iso: "BY" },
  { name: "Belgium", continent: "Europe", iso: "BE" },
  { name: "Belize", continent: "North America", iso: "BZ" },
  { name: "Benin", continent: "Africa", iso: "BJ" },
  { name: "Bermuda", continent: "North America", iso: "BM" },
  { name: "Bhutan", continent: "Asia", iso: "BT" },
  { name: "Bolivia", continent: "South America", iso: "BO" },
  { name: "Bosnia and Herzegovina", continent: "Europe", iso: "BA" },
  { name: "Botswana", continent: "Africa", iso: "BW" },
  { name: "Brazil", continent: "South America", iso: "BR" },
  { name: "Brunei", continent: "Asia", iso: "BN" },
  { name: "Bulgaria", continent: "Europe", iso: "BG" },
  { name: "Burkina Faso", continent: "Africa", iso: "BF" },
  { name: "Burundi", continent: "Africa", iso: "BI" },
  { name: "Cabo Verde", continent: "Africa", iso: "CV" },
  { name: "Cambodia", continent: "Asia", iso: "KH" },
  { name: "Cameroon", continent: "Africa", iso: "CM" },
  { name: "Canada", continent: "North America", iso: "CA" },
  { name: "Central African Republic", continent: "Africa", iso: "CF" },
  { name: "Chad", continent: "Africa", iso: "TD" },
  { name: "Chile", continent: "South America", iso: "CL" },
  { name: "China", continent: "Asia", iso: "CN" },
  { name: "Colombia", continent: "South America", iso: "CO" },
  { name: "Comoros", continent: "Africa", iso: "KM" },
  { name: "Congo", continent: "Africa", iso: "CG" },
  { name: "Cook Islands", continent: "Oceania", iso: "CK" },
  { name: "Costa Rica", continent: "North America", iso: "CR" },
  { name: "Croatia", continent: "Europe", iso: "HR" },
  { name: "Cuba", continent: "North America", iso: "CU" },
  { name: "Cyprus", continent: "Europe", iso: "CY" },
  { name: "Czech Republic", continent: "Europe", iso: "CZ" },
  { name: "Democratic Republic of the Congo", continent: "Africa", iso: "CD" },
  { name: "Denmark", continent: "Europe", iso: "DK" },
  { name: "Djibouti", continent: "Africa", iso: "DJ" },
  { name: "Dominica", continent: "North America", iso: "DM" },
  { name: "Dominican Republic", continent: "North America", iso: "DO" },
  { name: "East Timor", continent: "Asia", iso: "TL" },
  { name: "Ecuador", continent: "South America", iso: "EC" },
  { name: "Egypt", continent: "Africa", iso: "EG" },
  { name: "El Salvador", continent: "North America", iso: "SV" },
  { name: "Equatorial Guinea", continent: "Africa", iso: "GQ" },
  { name: "Eritrea", continent: "Africa", iso: "ER" },
  { name: "Estonia", continent: "Europe", iso: "EE" },
  { name: "Eswatini", continent: "Africa", iso: "SZ" },
  { name: "Ethiopia", continent: "Africa", iso: "ET" },
  { name: "Fiji", continent: "Oceania", iso: "FJ" },
  { name: "Finland", continent: "Europe", iso: "FI" },
  { name: "France", continent: "Europe", iso: "FR" },
  { name: "French Guiana", continent: "South America", iso: "GF" },
  { name: "Gabon", continent: "Africa", iso: "GA" },
  { name: "Gambia", continent: "Africa", iso: "GM" },
  { name: "Georgia", continent: "Asia", iso: "GE" },
  { name: "Germany", continent: "Europe", iso: "DE" },
  { name: "Ghana", continent: "Africa", iso: "GH" },
  { name: "Greece", continent: "Europe", iso: "GR" },
  { name: "Grenada", continent: "North America", iso: "GD" },
  { name: "Guatemala", continent: "North America", iso: "GT" },
  { name: "Guinea", continent: "Africa", iso: "GN" },
  { name: "Guinea-Bissau", continent: "Africa", iso: "GW" },
  { name: "Guyana", continent: "South America", iso: "GY" },
  { name: "Haiti", continent: "North America", iso: "HT" },
  { name: "Honduras", continent: "North America", iso: "HN" },
  { name: "Hungary", continent: "Europe", iso: "HU" },
  { name: "Iceland", continent: "Europe", iso: "IS" },
  { name: "India", continent: "Asia", iso: "IN" },
  { name: "Indonesia", continent: "Asia", iso: "ID" },
  { name: "Iran", continent: "Asia", iso: "IR" },
  { name: "Iraq", continent: "Asia", iso: "IQ" },
  { name: "Ireland", continent: "Europe", iso: "IE" },
  { name: "Italy", continent: "Europe", iso: "IT" },
  { name: "Ivory Coast", continent: "Africa", iso: "CI" },
  { name: "Jamaica", continent: "North America", iso: "JM" },
  { name: "Japan", continent: "Asia", iso: "JP" },
  { name: "Jordan", continent: "Asia", iso: "JO" },
  { name: "Kazakhstan", continent: "Asia", iso: "KZ" },
  { name: "Kenya", continent: "Africa", iso: "KE" },
  { name: "Kiribati", continent: "Oceania", iso: "KI" },
  { name: "Kosovo", continent: "Europe", iso: "XK" },
  { name: "Kuwait", continent: "Asia", iso: "KW" },
  { name: "Kyrgyzstan", continent: "Asia", iso: "KG" },
  { name: "Laos", continent: "Asia", iso: "LA" },
  { name: "Latvia", continent: "Europe", iso: "LV" },
  { name: "Lebanon", continent: "Asia", iso: "LB" },
  { name: "Lesotho", continent: "Africa", iso: "LS" },
  { name: "Liberia", continent: "Africa", iso: "LR" },
  { name: "Libya", continent: "Africa", iso: "LY" },
  { name: "Liechtenstein", continent: "Europe", iso: "LI" },
  { name: "Lithuania", continent: "Europe", iso: "LT" },
  { name: "Luxembourg", continent: "Europe", iso: "LU" },
  { name: "Madagascar", continent: "Africa", iso: "MG" },
  { name: "Malawi", continent: "Africa", iso: "MW" },
  { name: "Malaysia", continent: "Asia", iso: "MY" },
  { name: "Maldives", continent: "Asia", iso: "MV" },
  { name: "Mali", continent: "Africa", iso: "ML" },
  { name: "Malta", continent: "Europe", iso: "MT" },
  { name: "Marshall Islands", continent: "Oceania", iso: "MH" },
  { name: "Mauritania", continent: "Africa", iso: "MR" },
  { name: "Mauritius", continent: "Africa", iso: "MU" },
  { name: "Mexico", continent: "North America", iso: "MX" },
  { name: "Micronesia", continent: "Oceania", iso: "FM" },
  { name: "Moldova", continent: "Europe", iso: "MD" },
  { name: "Monaco", continent: "Europe", iso: "MC" },
  { name: "Mongolia", continent: "Asia", iso: "MN" },
  { name: "Montenegro", continent: "Europe", iso: "ME" },
  { name: "Morocco", continent: "Africa", iso: "MA" },
  { name: "Mozambique", continent: "Africa", iso: "MZ" },
  { name: "Myanmar", continent: "Asia", iso: "MM" },
  { name: "Namibia", continent: "Africa", iso: "NA" },
  { name: "Nauru", continent: "Oceania", iso: "NR" },
  { name: "Nepal", continent: "Asia", iso: "NP" },
  { name: "Netherlands", continent: "Europe", iso: "NL" },
  { name: "New Zealand", continent: "Oceania", iso: "NZ" },
  { name: "Nicaragua", continent: "North America", iso: "NI" },
  { name: "Niger", continent: "Africa", iso: "NE" },
  { name: "Nigeria", continent: "Africa", iso: "NG" },
  { name: "North Korea", continent: "Asia", iso: "KP" },
  { name: "North Macedonia", continent: "Europe", iso: "MK" },
  { name: "Norway", continent: "Europe", iso: "NO" },
  { name: "Oman", continent: "Asia", iso: "OM" },
  { name: "Pakistan", continent: "Asia", iso: "PK" },
  { name: "Palau", continent: "Oceania", iso: "PW" },
  { name: "Palestine", continent: "Asia", iso: "PS" },
  { name: "Panama", continent: "North America", iso: "PA" },
  { name: "Papua New Guinea", continent: "Oceania", iso: "PG" },
  { name: "Paraguay", continent: "South America", iso: "PY" },
  { name: "Peru", continent: "South America", iso: "PE" },
  { name: "Philippines", continent: "Asia", iso: "PH" },
  { name: "Poland", continent: "Europe", iso: "PL" },
  { name: "Portugal", continent: "Europe", iso: "PT" },
  { name: "Puerto Rico", continent: "North America", iso: "PR" },
  { name: "Qatar", continent: "Asia", iso: "QA" },
  { name: "Romania", continent: "Europe", iso: "RO" },
  { name: "Russia", continent: "Europe", iso: "RU" },
  { name: "Rwanda", continent: "Africa", iso: "RW" },
  { name: "Saint Kitts and Nevis", continent: "North America", iso: "KN" },
  { name: "Saint Lucia", continent: "North America", iso: "LC" },
  {
    name: "Saint Vincent and the Grenadines",
    continent: "North America",
    iso: "VC",
  },
  { name: "Samoa", continent: "Oceania", iso: "WS" },
  { name: "San Marino", continent: "Europe", iso: "SM" },
  { name: "Sao Tome and Principe", continent: "Africa", iso: "ST" },
  { name: "Saudi Arabia", continent: "Asia", iso: "SA" },
  { name: "Senegal", continent: "Africa", iso: "SN" },
  { name: "Serbia", continent: "Europe", iso: "RS" },
  { name: "Seychelles", continent: "Africa", iso: "SC" },
  { name: "Sierra Leone", continent: "Africa", iso: "SL" },
  { name: "Singapore", continent: "Asia", iso: "SG" },
  { name: "Slovakia", continent: "Europe", iso: "SK" },
  { name: "Slovenia", continent: "Europe", iso: "SI" },
  { name: "Solomon Islands", continent: "Oceania", iso: "SB" },
  { name: "Somalia", continent: "Africa", iso: "SO" },
  { name: "South Africa", continent: "Africa", iso: "ZA" },
  { name: "South Korea", continent: "Asia", iso: "KR" },
  { name: "South Sudan", continent: "Africa", iso: "SS" },
  { name: "Spain", continent: "Europe", iso: "ES" },
  { name: "Sri Lanka", continent: "Asia", iso: "LK" },
  { name: "Sudan", continent: "Africa", iso: "SD" },
  { name: "Suriname", continent: "South America", iso: "SR" },
  { name: "Sweden", continent: "Europe", iso: "SE" },
  { name: "Switzerland", continent: "Europe", iso: "CH" },
  { name: "Syria", continent: "Asia", iso: "SY" },
  { name: "Taiwan", continent: "Asia", iso: "TW" },
  { name: "Tajikistan", continent: "Asia", iso: "TJ" },
  { name: "Tanzania", continent: "Africa", iso: "TZ" },
  { name: "Thailand", continent: "Asia", iso: "TH" },
  { name: "Timor-Leste", continent: "Asia", iso: "TL" },
  { name: "Togo", continent: "Africa", iso: "TG" },
  { name: "Tonga", continent: "Oceania", iso: "TO" },
  { name: "Trinidad and Tobago", continent: "North America", iso: "TT" },
  { name: "Tunisia", continent: "Africa", iso: "TN" },
  { name: "Turkey", continent: "Asia", iso: "TR" },
  { name: "Turkmenistan", continent: "Asia", iso: "TM" },
  { name: "Tuvalu", continent: "Oceania", iso: "TV" },
  { name: "Uganda", continent: "Africa", iso: "UG" },
  { name: "Ukraine", continent: "Europe", iso: "UA" },
  { name: "United Arab Emirates", continent: "Asia", iso: "AE" },
  { name: "United Kingdom", continent: "Europe", iso: "GB" },
  { name: "United States", continent: "North America", iso: "US" },
  { name: "Uruguay", continent: "South America", iso: "UY" },
  { name: "Uzbekistan", continent: "Asia", iso: "UZ" },
  { name: "Vanuatu", continent: "Oceania", iso: "VU" },
  { name: "Vatican City", continent: "Europe", iso: "VA" },
  { name: "Venezuela", continent: "South America", iso: "VE" },
  { name: "Vietnam", continent: "Asia", iso: "VN" },
  { name: "Western Sahara", continent: "Africa", iso: "EH" },
  { name: "Yemen", continent: "Asia", iso: "YE" },
  { name: "Zambia", continent: "Africa", iso: "ZM" },
  { name: "Zimbabwe", continent: "Africa", iso: "ZW" },
];

export const COUNTRIES = COUNTRY_DATA.map((c) => c.name);

export function getCountriesByContinent() {
  const continents = {
    Africa: [] as string[],
    Asia: [] as string[],
    Europe: [] as string[],
    "North America": [] as string[],
    "South America": [] as string[],
    Oceania: [] as string[],
  };

  COUNTRY_DATA.forEach((country) => {
    continents[country.continent].push(country.name);
  });

  // Sort each continent's countries
  Object.keys(continents).forEach((continent) => {
    continents[continent as keyof typeof continents].sort();
  });

  return continents;
}

export function getCountryISO(countryName: string): string | undefined {
  const result = COUNTRY_DATA.find((c) => c.name === countryName)?.iso;
  if (countryName === "Greenland") {
    console.log("[Countries] Getting ISO for Greenland:", result);
  }
  return result;
}
