const ALL_COUNTRIES = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Greenland",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Bermuda",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cayman Islands",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Cook Islands",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Czechia",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Falkland Islands",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guadeloupe",
  "Guatemala",
  "Guinea",
  "Guinea Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

// Common alternative names for matching
export const COUNTRY_ALIASES: Record<string, string[]> = {
  "United States": [
    "USA",
    "US",
    "United States of America",
    "America",
    "U.S.A",
    "U.S",
    "States",
  ],
  "United Kingdom": ["UK", "Britain", "Great Britain", "England", "U.K", "GB"],
  "Democratic Republic of the Congo": [
    "DRC",
    "DR Congo",
    "Congo-Kinshasa",
    "Congo Kinshasa",
    "Zaire",
  ],
  Congo: [
    "Republic of Congo",
    "Congo-Brazzaville",
    "Congo Brazzaville",
    "Republic of the Congo",
  ],
  "Ivory Coast": [
    "Cote d'Ivoire",
    "Cote d Ivoire",
    "Cote dIvoire",
    "Côte d'Ivoire",
  ],
  "North Korea": ["DPRK", "Democratic People's Republic of Korea", "NK"],
  "South Korea": ["Korea", "Republic of Korea", "ROK", "SK", "S Korea"],
  "Czech Republic": ["Czechia"],
  "East Timor": ["Timor-Leste", "Timor Leste", "Timor"],
  Myanmar: ["Burma"],
  "Cabo Verde": ["Cape Verde"],
  Eswatini: ["Swaziland"],
  "North Macedonia": ["Macedonia", "FYROM"],
  "United Arab Emirates": ["UAE", "Emirates", "U.A.E"],
  "Bosnia and Herzegovina": ["Bosnia", "BiH"],
  "Trinidad and Tobago": ["Trinidad", "T&T"],
  "Saint Kitts and Nevis": ["St Kitts", "Saint Kitts", "SKN"],
  "Saint Lucia": ["St Lucia"],
  "Saint Vincent and the Grenadines": ["St Vincent", "Saint Vincent", "SVG"],
  "Sao Tome and Principe": ["Sao Tome", "São Tomé"],
  "Papua New Guinea": ["PNG"],
  Netherlands: ["Holland"],
  Switzerland: ["Swiss"],
  Russia: ["Russian Federation"],
  "South Africa": ["RSA", "SA"],
  "New Zealand": ["NZ", "Kiwi"],
  Australia: ["Aus", "Oz"],
  Tanzania: ["TZ"],
  "Central African Republic": ["CAR"],
  "Dominican Republic": ["DR"],
};

export function normalizeCountryName(input: string): string {
  return input
    .toLowerCase()
    .trim()
    .replace(/[^a-z\s]/g, "");
}

export function findCountryMatch(input: string): string | null {
  const normalized = normalizeCountryName(input);

  // Direct match
  for (const country of ALL_COUNTRIES) {
    if (normalizeCountryName(country) === normalized) {
      return country;
    }
  }

  // Alias match
  for (const [country, aliases] of Object.entries(COUNTRY_ALIASES)) {
    for (const alias of aliases) {
      if (normalizeCountryName(alias) === normalized) {
        return country;
      }
    }
  }

  return null;
}

export interface CountryData {
  name: string;
  continent:
    | "Africa"
    | "Asia"
    | "Europe"
    | "North America"
    | "South America"
    | "Oceania";
  iso: string;
}

export const COUNTRY_DATA: CountryData[] = [
  { name: "Afghanistan", continent: "Asia", iso: "AF" },
  { name: "Albania", continent: "Europe", iso: "AL" },
  { name: "Algeria", continent: "Africa", iso: "DZ" },
  { name: "Greenland", continent: "North America", iso: "GL" },
  { name: "Andorra", continent: "Europe", iso: "AD" },
  { name: "Angola", continent: "Africa", iso: "AO" },
  { name: "Antigua and Barbuda", continent: "North America", iso: "AG" },
  { name: "Argentina", continent: "South America", iso: "AR" },
  { name: "Armenia", continent: "Asia", iso: "AM" },
  { name: "Australia", continent: "Oceania", iso: "AU" },
  { name: "Austria", continent: "Europe", iso: "AT" },
  { name: "Azerbaijan", continent: "Asia", iso: "AZ" },
  { name: "Bahamas", continent: "North America", iso: "BS" },
  { name: "Bahrain", continent: "Asia", iso: "BH" },
  { name: "Bangladesh", continent: "Asia", iso: "BD" },
  { name: "Barbados", continent: "North America", iso: "BB" },
  { name: "Belarus", continent: "Europe", iso: "BY" },
  { name: "Belgium", continent: "Europe", iso: "BE" },
  { name: "Belize", continent: "North America", iso: "BZ" },
  { name: "Benin", continent: "Africa", iso: "BJ" },
  { name: "Bhutan", continent: "Asia", iso: "BT" },
  { name: "Bolivia", continent: "South America", iso: "BO" },
  { name: "Bosnia and Herzegovina", continent: "Europe", iso: "BA" },
  { name: "Botswana", continent: "Africa", iso: "BW" },
  { name: "Brazil", continent: "South America", iso: "BR" },
  { name: "Brunei", continent: "Asia", iso: "BN" },
  { name: "Bulgaria", continent: "Europe", iso: "BG" },
  { name: "Burkina Faso", continent: "Africa", iso: "BF" },
  { name: "Burundi", continent: "Africa", iso: "BI" },
  { name: "Cabo Verde", continent: "Africa", iso: "CV" },
  { name: "Cambodia", continent: "Asia", iso: "KH" },
  { name: "Cameroon", continent: "Africa", iso: "CM" },
  { name: "Canada", continent: "North America", iso: "CA" },
  { name: "Central African Republic", continent: "Africa", iso: "CF" },
  { name: "Chad", continent: "Africa", iso: "TD" },
  { name: "Chile", continent: "South America", iso: "CL" },
  { name: "China", continent: "Asia", iso: "CN" },
  { name: "Colombia", continent: "South America", iso: "CO" },
  { name: "Comoros", continent: "Africa", iso: "KM" },
  { name: "Congo", continent: "Africa", iso: "CG" },
  { name: "Costa Rica", continent: "North America", iso: "CR" },
  { name: "Croatia", continent: "Europe", iso: "HR" },
  { name: "Cuba", continent: "North America", iso: "CU" },
  { name: "Cyprus", continent: "Europe", iso: "CY" },
  { name: "Czech Republic", continent: "Europe", iso: "CZ" },
  { name: "Czechia", continent: "Europe", iso: "CZ" },
  { name: "Democratic Republic of the Congo", continent: "Africa", iso: "CD" },
  { name: "Denmark", continent: "Europe", iso: "DK" },
  { name: "Djibouti", continent: "Africa", iso: "DJ" },
  { name: "Dominica", continent: "North America", iso: "DM" },
  { name: "Dominican Republic", continent: "North America", iso: "DO" },
  { name: "East Timor", continent: "Asia", iso: "TL" },
  { name: "Ecuador", continent: "South America", iso: "EC" },
  { name: "Egypt", continent: "Africa", iso: "EG" },
  { name: "El Salvador", continent: "North America", iso: "SV" },
  { name: "Equatorial Guinea", continent: "Africa", iso: "GQ" },
  { name: "Eritrea", continent: "Africa", iso: "ER" },
  { name: "Estonia", continent: "Europe", iso: "EE" },
  { name: "Eswatini", continent: "Africa", iso: "SZ" },
  { name: "Ethiopia", continent: "Africa", iso: "ET" },
  { name: "Fiji", continent: "Oceania", iso: "FJ" },
  { name: "Finland", continent: "Europe", iso: "FI" },
  { name: "France", continent: "Europe", iso: "FR" },
  { name: "Gabon", continent: "Africa", iso: "GA" },
  { name: "Gambia", continent: "Africa", iso: "GM" },
  { name: "Georgia", continent: "Asia", iso: "GE" },
  { name: "Germany", continent: "Europe", iso: "DE" },
  { name: "Ghana", continent: "Africa", iso: "GH" },
  { name: "Greece", continent: "Europe", iso: "GR" },
  { name: "Grenada", continent: "North America", iso: "GD" },
  { name: "Guatemala", continent: "North America", iso: "GT" },
  { name: "Guinea", continent: "Africa", iso: "GN" },
  { name: "Guinea-Bissau", continent: "Africa", iso: "GW" },
  { name: "Guyana", continent: "South America", iso: "GY" },
  { name: "Haiti", continent: "North America", iso: "HT" },
  { name: "Honduras", continent: "North America", iso: "HN" },
  { name: "Hungary", continent: "Europe", iso: "HU" },
  { name: "Iceland", continent: "Europe", iso: "IS" },
  { name: "India", continent: "Asia", iso: "IN" },
  { name: "Indonesia", continent: "Asia", iso: "ID" },
  { name: "Iran", continent: "Asia", iso: "IR" },
  { name: "Iraq", continent: "Asia", iso: "IQ" },
  { name: "Ireland", continent: "Europe", iso: "IE" },
  { name: "Italy", continent: "Europe", iso: "IT" },
  { name: "Ivory Coast", continent: "Africa", iso: "CI" },
  { name: "Jamaica", continent: "North America", iso: "JM" },
  { name: "Japan", continent: "Asia", iso: "JP" },
  { name: "Jordan", continent: "Asia", iso: "JO" },
  { name: "Kazakhstan", continent: "Asia", iso: "KZ" },
  { name: "Kenya", continent: "Africa", iso: "KE" },
  { name: "Kiribati", continent: "Oceania", iso: "KI" },
  { name: "Kosovo", continent: "Europe", iso: "XK" },
  { name: "Kuwait", continent: "Asia", iso: "KW" },
  { name: "Kyrgyzstan", continent: "Asia", iso: "KG" },
  { name: "Laos", continent: "Asia", iso: "LA" },
  { name: "Latvia", continent: "Europe", iso: "LV" },
  { name: "Lebanon", continent: "Asia", iso: "LB" },
  { name: "Lesotho", continent: "Africa", iso: "LS" },
  { name: "Liberia", continent: "Africa", iso: "LR" },
  { name: "Libya", continent: "Africa", iso: "LY" },
  { name: "Liechtenstein", continent: "Europe", iso: "LI" },
  { name: "Lithuania", continent: "Europe", iso: "LT" },
  { name: "Luxembourg", continent: "Europe", iso: "LU" },
  { name: "Madagascar", continent: "Africa", iso: "MG" },
  { name: "Malawi", continent: "Africa", iso: "MW" },
  { name: "Malaysia", continent: "Asia", iso: "MY" },
  { name: "Maldives", continent: "Asia", iso: "MV" },
  { name: "Mali", continent: "Africa", iso: "ML" },
  { name: "Malta", continent: "Europe", iso: "MT" },
  { name: "Marshall Islands", continent: "Oceania", iso: "MH" },
  { name: "Mauritania", continent: "Africa", iso: "MR" },
  { name: "Mauritius", continent: "Africa", iso: "MU" },
  { name: "Mexico", continent: "North America", iso: "MX" },
  { name: "Micronesia", continent: "Oceania", iso: "FM" },
  { name: "Moldova", continent: "Europe", iso: "MD" },
  { name: "Monaco", continent: "Europe", iso: "MC" },
  { name: "Mongolia", continent: "Asia", iso: "MN" },
  { name: "Montenegro", continent: "Europe", iso: "ME" },
  { name: "Morocco", continent: "Africa", iso: "MA" },
  { name: "Mozambique", continent: "Africa", iso: "MZ" },
  { name: "Myanmar", continent: "Asia", iso: "MM" },
  { name: "Namibia", continent: "Africa", iso: "NA" },
  { name: "Nauru", continent: "Oceania", iso: "NR" },
  { name: "Nepal", continent: "Asia", iso: "NP" },
  { name: "Netherlands", continent: "Europe", iso: "NL" },
  { name: "New Zealand", continent: "Oceania", iso: "NZ" },
  { name: "Nicaragua", continent: "North America", iso: "NI" },
  { name: "Niger", continent: "Africa", iso: "NE" },
  { name: "Nigeria", continent: "Africa", iso: "NG" },
  { name: "North Korea", continent: "Asia", iso: "KP" },
  { name: "North Macedonia", continent: "Europe", iso: "MK" },
  { name: "Norway", continent: "Europe", iso: "NO" },
  { name: "Oman", continent: "Asia", iso: "OM" },
  { name: "Pakistan", continent: "Asia", iso: "PK" },
  { name: "Palau", continent: "Oceania", iso: "PW" },
  { name: "Palestine", continent: "Asia", iso: "PS" },
  { name: "Panama", continent: "North America", iso: "PA" },
  { name: "Papua New Guinea", continent: "Oceania", iso: "PG" },
  { name: "Paraguay", continent: "South America", iso: "PY" },
  { name: "Peru", continent: "South America", iso: "PE" },
  { name: "Philippines", continent: "Asia", iso: "PH" },
  { name: "Poland", continent: "Europe", iso: "PL" },
  { name: "Portugal", continent: "Europe", iso: "PT" },
  { name: "Qatar", continent: "Asia", iso: "QA" },
  { name: "Romania", continent: "Europe", iso: "RO" },
  { name: "Russia", continent: "Europe", iso: "RU" },
  { name: "Rwanda", continent: "Africa", iso: "RW" },
  { name: "Saint Kitts and Nevis", continent: "North America", iso: "KN" },
  { name: "Saint Lucia", continent: "North America", iso: "LC" },
  {
    name: "Saint Vincent and the Grenadines",
    continent: "North America",
    iso: "VC",
  },
  { name: "Samoa", continent: "Oceania", iso: "WS" },
  { name: "San Marino", continent: "Europe", iso: "SM" },
  { name: "Sao Tome and Principe", continent: "Africa", iso: "ST" },
  { name: "Saudi Arabia", continent: "Asia", iso: "SA" },
  { name: "Senegal", continent: "Africa", iso: "SN" },
  { name: "Serbia", continent: "Europe", iso: "RS" },
  { name: "Seychelles", continent: "Africa", iso: "SC" },
  { name: "Sierra Leone", continent: "Africa", iso: "SL" },
  { name: "Singapore", continent: "Asia", iso: "SG" },
  { name: "Slovakia", continent: "Europe", iso: "SK" },
  { name: "Slovenia", continent: "Europe", iso: "SI" },
  { name: "Solomon Islands", continent: "Oceania", iso: "SB" },
  { name: "Somalia", continent: "Africa", iso: "SO" },
  { name: "South Africa", continent: "Africa", iso: "ZA" },
  { name: "South Korea", continent: "Asia", iso: "KR" },
  { name: "South Sudan", continent: "Africa", iso: "SS" },
  { name: "Spain", continent: "Europe", iso: "ES" },
  { name: "Sri Lanka", continent: "Asia", iso: "LK" },
  { name: "Sudan", continent: "Africa", iso: "SD" },
  { name: "Suriname", continent: "South America", iso: "SR" },
  { name: "Sweden", continent: "Europe", iso: "SE" },
  { name: "Switzerland", continent: "Europe", iso: "CH" },
  { name: "Syria", continent: "Asia", iso: "SY" },
  { name: "Taiwan", continent: "Asia", iso: "TW" },
  { name: "Tajikistan", continent: "Asia", iso: "TJ" },
  { name: "Tanzania", continent: "Africa", iso: "TZ" },
  { name: "Thailand", continent: "Asia", iso: "TH" },
  { name: "Timor-Leste", continent: "Asia", iso: "TL" },
  { name: "Togo", continent: "Africa", iso: "TG" },
  { name: "Tonga", continent: "Oceania", iso: "TO" },
  { name: "Trinidad and Tobago", continent: "North America", iso: "TT" },
  { name: "Tunisia", continent: "Africa", iso: "TN" },
  { name: "Turkey", continent: "Asia", iso: "TR" },
  { name: "Turkmenistan", continent: "Asia", iso: "TM" },
  { name: "Tuvalu", continent: "Oceania", iso: "TV" },
  { name: "Uganda", continent: "Africa", iso: "UG" },
  { name: "Ukraine", continent: "Europe", iso: "UA" },
  { name: "United Arab Emirates", continent: "Asia", iso: "AE" },
  { name: "United Kingdom", continent: "Europe", iso: "GB" },
  { name: "United States", continent: "North America", iso: "US" },
  { name: "Uruguay", continent: "South America", iso: "UY" },
  { name: "Uzbekistan", continent: "Asia", iso: "UZ" },
  { name: "Vanuatu", continent: "Oceania", iso: "VU" },
  { name: "Vatican City", continent: "Europe", iso: "VA" },
  { name: "Venezuela", continent: "South America", iso: "VE" },
  { name: "Vietnam", continent: "Asia", iso: "VN" },
  { name: "Yemen", continent: "Asia", iso: "YE" },
  { name: "Zambia", continent: "Africa", iso: "ZM" },
  { name: "Zimbabwe", continent: "Africa", iso: "ZW" },
];

export const COUNTRIES = COUNTRY_DATA.map((c) => c.name);

export function getCountriesByContinent() {
  const continents = {
    Africa: [] as string[],
    Asia: [] as string[],
    Europe: [] as string[],
    "North America": [] as string[],
    "South America": [] as string[],
    Oceania: [] as string[],
  };

  COUNTRY_DATA.forEach((country) => {
    continents[country.continent].push(country.name);
  });

  // Sort each continent's countries
  Object.keys(continents).forEach((continent) => {
    continents[continent as keyof typeof continents].sort();
  });

  return continents;
}

export function getCountryISO(countryName: string): string | undefined {
  const result = COUNTRY_DATA.find((c) => c.name === countryName)?.iso;
  if (countryName === "Greenland") {
    console.log("[Countries] Getting ISO for Greenland:", result);
  }
  return result;
}
